apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: budget-service
  template:
    metadata:
      labels:
        app: budget-service
    spec:
      containers:
        - name: budget
          image: budget-service:local
          ports:
            - containerPort: 4002
          env:
            - name: PORT
              value: "4002"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt

            - name: MONGO_URI
              value: "mongodb://mongo:27017/budget_db"
