apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expense-service
  template:
    metadata:
      labels:
        app: expense-service
    spec:
      containers:
        - name: expense
          image: expense-service:local
          ports:
            - containerPort: 4003
          env:
            - name: PORT
              value: "4003"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt

            - name: MONGO_URI
              value: "mongodb://mongo:27017/expense_db"
