apiVersion: apps/v1
kind: Deployment
metadata:
  name: investment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: investment-service
  template:
    metadata:
      labels:
        app: investment-service
    spec:
      containers:
        - name: investment
          image: investment-service:local
          ports:
            - containerPort: 4004
          env:
            - name: PORT
              value: "4004"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt

            - name: MONGO_URI
              value: "mongodb://mongo:27017/investment_db"
