apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: report-service
  template:
    metadata:
      labels:
        app: report-service
    spec:
      containers:
        - name: report
          image: report-service:local
          ports:
            - containerPort: 4005
          env:
            - name: PORT
              value: "4005"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt

            - name: MONGO_URI
              value: "mongodb://mongo:27017/report_db"
